# Generated by Django 3.2.4 on 2021-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(db_column='Card_ID', primary_key=True, serialize=False)),
                ('ctitle', models.TextField(db_column='cTitle')),
                ('caddress', models.TextField(blank=True, db_column='cAddress', null=True)),
                ('cdescription', models.TextField(blank=True, db_column='cDescription', null=True)),
                ('cImage', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'CARD',
                'managed': True,
            },
        ),
    ]
