# Generated by Django 3.2.4 on 2021-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='caddress',
            new_name='cAddress',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cdescription',
            new_name='cDescription',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_id',
            new_name='card_ID',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ctitle',
        ),
        migrations.AddField(
            model_name='card',
            name='cTitle',
            field=models.TextField(db_column='cTitle', default=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='card',
            name='cImage',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
