# Generated by Django 3.2.4 on 2021-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20211003_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cTitle',
            field=models.TextField(db_column='cTitle', default='', max_length=14),
        ),
    ]
