# Generated by Django 3.2.4 on 2021-10-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_card_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(default='', max_length=255, unique=True)),
                ('password', models.TextField(default='', max_length=255)),
            ],
        ),
    ]
