CREATE TABLE IF NOT EXISTS CARD (
    Card_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    cTitle NVARCHAR(20) NOT NULL,
    cAddress NVARCHAR(255),
    cDescription TEXT,
    cImage NVARCHAR(255)
);