# Generated by Django 3.2.4 on 2021-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_card_ctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cImage',
            field=models.ImageField(upload_to='staticfiles/img/'),
        ),
    ]
